### PR TITLE
(WIP) The real NYC data

### PR DESCRIPTION
**Pull request by briandfoy**
This is a work in progress. The current data is just not how anyone in New York thinks about this, including the Metropolitan Transit Authority (MTA). That's not a big deal because they have [data downloads](https://catalog.data.gov/dataset/mta-subway-stations).

There are some things to work out:

- [ ] some stations far away from each other have the same name
- [ ] some lines bifurcate at the ends (A, 5)
- [ ] some lines have the same train name, but are not the same trains (there are three different S trains that do not use the same tracks and are no where near each other)
- [ ] some separate stations are connected by pedestrian tunnels such that you don't have to leave the pay area, and people prefer to use those rather than exiting, walking, and entering again.
- [ ] I don't think the MTA provides solid data on previous and next stations. maybe they do and I don't see it. The stations are generally in sequence, but with holes, and one main line is used as an identifier.

So, I'm working to recreate the XML data from the MTA data.

### CODE REVIEW

**Comment by briandfoy** [comment]
Also, I'd be happy to be a contributor in the main repo, too.

**Comment by manwar** [comment]
@briandfoy No need to even look at your changes. If is coming from you then it must be good enough. I am so happy to have you as contributor to the library. Your contribution is always appreciated.

**Comment by briandfoy** [comment]
Oh, you shouldn't have merged this since it's a work in progress. It's basically a mess right now, has all the problems I listed, and is broken.

Since no one else is likely looking at this, I'd revert master to its previous state and force push to GitHub.

And, anyone should always look at my changes. I can do stupid, or stupider stuff, than the average person.

**Comment by manwar** [comment]
@briandfoy done as per your suggestion. hopefully we are good to go for now.

**Pull request merged**
